<template>
  <section class="workspace">
    <header class="workspace-header"><div><h1>Knowledge</h1><p class="muted">Upload and maintain the documents used by retrieval-augmented chat.</p></div><div class="header-actions"><button type="button" :disabled="loading" @click="refresh">{{ loading ? 'Refreshing...' : 'Refresh' }}</button><button type="button" :disabled="rebuilding" @click="rebuild">{{ rebuilding ? 'Rebuilding...' : 'Rebuild index' }}</button></div></header>
    <p v-if="error" class="status-error">{{ error }}</p><p v-if="uploadError" class="status-error">Upload: {{ uploadError }}</p>
    <div class="workspace-grid">
      <div class="stack">
        <WorkbenchSection title="Upload document" class="panel"><input ref="fileInput" type="file" @change="chooseFile" /><input v-model="source" placeholder="Source (optional)" /><input v-model="tags" placeholder="Tags, comma separated (optional)" /><button type="button" :disabled="uploading || !pendingFile" @click="upload">{{ uploading ? 'Uploading...' : 'Upload selected file' }}</button><p v-if="pendingFile" class="muted">{{ pendingFile.name }}</p></WorkbenchSection>
        <WorkbenchSection title="Documents" class="panel list-panel"><p v-if="loading" class="muted">Loading documents...</p><p v-else-if="!documents.length" class="muted">No documents yet. Upload a file to begin.</p><button v-for="document in documents" v-else :key="document.documentId" type="button" :class="['document-row', { selected: selectedId === document.documentId }]" @click="selectDocument(document.documentId)"><strong>{{ document.fileName || document.documentId }}</strong><span>{{ document.status || 'Unknown' }} · {{ document.chunkCount ?? 0 }} chunks</span></button></WorkbenchSection>
      </div>
      <WorkbenchSection title="Document detail" class="panel detail-panel"><p v-if="detailLoading" class="muted">Loading document detail...</p><p v-else-if="!selected" class="muted">Select a document from the list to inspect its metadata and actions.</p><template v-else><dl><div><dt>Name</dt><dd>{{ selected.fileName || '-' }}</dd></div><div><dt>Status</dt><dd>{{ selected.status || '-' }}</dd></div><div><dt>Source</dt><dd>{{ selected.source || '-' }}</dd></div><div><dt>Tags</dt><dd>{{ selected.tags || '-' }}</dd></div><div><dt>Chunks</dt><dd>{{ selected.chunkCount ?? 0 }}</dd></div><div><dt>Uploaded</dt><dd>{{ formatTime(selected.uploadedAt) }}</dd></div></dl><p v-if="selected.errorMessage" class="status-error">{{ selected.errorMessage }}</p><div class="header-actions"><button type="button" :disabled="acting" @click="reprocess">{{ acting ? 'Processing...' : 'Reprocess' }}</button><button type="button" class="danger" :disabled="acting" @click="remove">Delete document</button></div><pre v-if="selected.content || selected.text">{{ selected.content || selected.text }}</pre></template></WorkbenchSection>
    </div>
  </section>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import WorkbenchSection from '../../components/workbench/WorkbenchSection.vue'
import { deleteKbDocument, getKbDocument, listKbDocuments, rebuildKbIndex, reprocessKbDocument, uploadKbDocument } from '../../services/api'

const documents = ref([]); const selected = ref(null); const selectedId = ref(''); const pendingFile = ref(null); const source = ref(''); const tags = ref(''); const error = ref(''); const uploadError = ref(''); const loading = ref(false); const detailLoading = ref(false); const uploading = ref(false); const rebuilding = ref(false); const acting = ref(false)
const report = (cause, fallback) => { error.value = cause?.message || fallback }
const refresh = async () => { loading.value = true; error.value = ''; try { documents.value = await listKbDocuments(80); if (selectedId.value && !documents.value.some((item) => item.documentId === selectedId.value)) { selectedId.value = ''; selected.value = null } } catch (cause) { report(cause, 'Document list could not be loaded.') } finally { loading.value = false } }
const selectDocument = async (id) => { selectedId.value = id; selected.value = null; detailLoading.value = true; error.value = ''; try { selected.value = await getKbDocument(id) } catch (cause) { report(cause, 'Document detail could not be loaded.') } finally { detailLoading.value = false } }
const chooseFile = (event) => { pendingFile.value = event.target.files?.[0] || null; event.target.value = '' }
const upload = async () => { if (!pendingFile.value) return; uploading.value = true; uploadError.value = ''; try { const result = await uploadKbDocument(pendingFile.value, { source: source.value || undefined, tags: tags.value || undefined }); pendingFile.value = null; await refresh(); if (result?.documentId) await selectDocument(result.documentId) } catch (cause) { uploadError.value = cause?.message || 'Document upload failed.' } finally { uploading.value = false } }
const reprocess = async () => { if (!selectedId.value) return; acting.value = true; error.value = ''; try { await reprocessKbDocument(selectedId.value); await refresh(); await selectDocument(selectedId.value) } catch (cause) { report(cause, 'Document reprocess failed.') } finally { acting.value = false } }
const remove = async () => { if (!selectedId.value || !window.confirm(`Delete ${selected.value?.fileName || 'this document'}?`)) return; acting.value = true; error.value = ''; try { await deleteKbDocument(selectedId.value); selectedId.value = ''; selected.value = null; await refresh() } catch (cause) { report(cause, 'Document deletion failed.') } finally { acting.value = false } }
const rebuild = async () => { rebuilding.value = true; error.value = ''; try { await rebuildKbIndex(); await refresh() } catch (cause) { report(cause, 'Index rebuild failed.') } finally { rebuilding.value = false } }
const formatTime = (value) => value ? new Date(value).toLocaleString() : '-'
onMounted(refresh)
</script>

<style scoped>
.workspace { display: grid; gap: 16px; padding: 20px; }.workspace-header, .header-actions { display: flex; align-items: center; justify-content: space-between; gap: 10px; }.workspace-header h1 { margin: 0 0 4px; font-size: 1.2rem; }.workspace-header p { margin: 0; }.workspace-grid { display: grid; grid-template-columns: minmax(260px, .8fr) minmax(0, 1.2fr); gap: 16px; }.stack, .panel { display: grid; align-content: start; gap: 10px; }.stack { gap: 16px; }.panel input { width: 100%; padding: 9px; color: var(--color-text); background: var(--color-bg); border: 1px solid var(--color-border); border-radius: var(--radius-sm); }.document-row { display: grid; gap: 4px; width: 100%; padding: 10px; text-align: left; background: var(--color-bg); border: 1px solid var(--color-border); border-radius: var(--radius-sm); }.document-row.selected { border-color: var(--color-primary); }.document-row span { color: var(--color-text-muted); font-size: .78rem; }.detail-panel dl { display: grid; gap: 8px; margin: 0; }.detail-panel dl div { display: grid; grid-template-columns: 100px 1fr; gap: 10px; }.detail-panel dt { color: var(--color-text-muted); }.detail-panel dd { margin: 0; overflow-wrap: anywhere; }.detail-panel pre { max-height: 300px; margin: 0; overflow: auto; white-space: pre-wrap; overflow-wrap: anywhere; padding: 10px; background: var(--color-bg); border: 1px solid var(--color-border); border-radius: var(--radius-sm); font-size: .78rem; }.status-error { margin: 0; color: var(--color-danger); }.danger { color: var(--color-danger); }button { cursor: pointer; }button:disabled { opacity: .55; cursor: not-allowed; }@media (max-width: 800px) { .workspace { padding: 14px; }.workspace-header, .workspace-grid { align-items: flex-start; grid-template-columns: 1fr; }.workspace-header { flex-direction: column; } }
</style>
